version: '3.8'

services:
  # 1. FastAPI Web Server
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: cleanpixel_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - DEBUG=False
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - cleanpixel_storage:/workspace/storage
    depends_on:
      - redis

  # 2. Celery Async Task Worker (Inpainting / Video Processing)
  celery_worker:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: cleanpixel_celery_worker
    restart: always
    command: celery -A app.services.celery_tasks.celery_app worker --loglevel=info --concurrency=2
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - cleanpixel_storage:/workspace/storage
    depends_on:
      - redis

  # 3. Redis In-Memory Broker & Cache
  redis:
    image: redis:7.2-alpine
    container_name: cleanpixel_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  cleanpixel_storage:
  redis_data:
